openapi: 3.0.0
info:
  title: IGCServer API
  description: REST API for storing and managing IGC files
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /:
    get:
      summary: Web interface for managing IGC files
      responses:
        '200':
          description: HTML page
          content:
            text/html:
              schema:
                type: string
  /igc/:
    get:
      summary: List all IGC files
      responses:
        '200':
          description: A list of IGC files with metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IGCInfo'
  /igc/upload:
    post:
      summary: Upload a new IGC or ZIP file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The IGC or ZIP file to upload
      responses:
        '303':
          description: Redirect to the main page after successful upload.
        '400':
          description: Invalid file type
  /igc/{filename}:
    get:
      summary: Download an IGC file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The IGC file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
    delete:
      summary: Delete an IGC file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '303':
          description: Redirect to the main page after successful deletion.
        '404':
          description: File not found
  /igc/delete-selected:
    post:
      summary: Delete selected IGC files
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                selected_files:
                  type: array
                  items:
                    type: string
      responses:
        '303':
          description: Redirect to the main page after successful deletion.
  /igc/download-selected:
    post:
      summary: Download selected IGC files as a ZIP archive
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                selected_files:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: A ZIP file containing the selected IGC files
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '303':
          description: Redirect if no files are selected.
components:
  schemas:
    IGCInfo:
      type: object
      properties:
        filename:
          type: string
        pilot:
          type: string
        date:
          type: string
        start_time:
          type: string
        datetime:
          type: string
        duration:
          type: string
        location:
          type: string
        glider_model:
          type: string
